'use client';

import Link from 'next/link';
import {
  AlertTriangle, ArrowRight, BrainCircuit, Check, ChevronDown, CircleCheck, Code2,
  FileSearch, Fingerprint, Globe2, KeyRound, LockKeyhole, Menu, PackageCheck, Radar,
  ScanLine, Shield, ShieldCheck, Sparkles, X,
} from 'lucide-react';
import { useState } from 'react';

const capabilities = ['SOURCE CODE', 'SECRETS', 'DEPENDENCIES', 'WEBSITES', 'RISK ANALYSIS', 'AI SECURITY'];
const features = [
  { icon: Code2, number: '01', title: 'Source Code Scanning', description: 'Analyze authorized repositories and local project paths for security issues and exposed sensitive information.' },
  { icon: KeyRound, number: '02', title: 'Secret Detection', description: 'Detect exposed API keys, credentials, tokens, private keys, database credentials, and other sensitive secrets.' },
  { icon: PackageCheck, number: '03', title: 'Dependency Security', description: 'Identify vulnerable package versions and security risks across dependency manifests.' },
  { icon: Globe2, number: '04', title: 'Website Security', description: 'Assess authorized web applications and services for common security weaknesses.' },
  { icon: AlertTriangle, number: '05', title: 'Risk Prioritization', description: 'Organize findings by severity, confidence, risk, and security impact.' },
  { icon: BrainCircuit, number: '06', title: 'AI Security Analysis', description: 'Use AI-assisted analysis to understand findings, investigate risks, and generate practical remediation guidance.' },
];
const steps = [
  { icon: Fingerprint, title: 'Register', description: 'Define the authorized project and target asset.' },
  { icon: ScanLine, title: 'Scan', description: 'Run analysis against code, websites, secrets, or dependencies.' },
  { icon: Radar, title: 'Analyze', description: 'Normalize findings and prioritize security risks.' },
  { icon: ShieldCheck, title: 'Remediate', description: 'Review evidence and follow actionable recommendations.' },
];
const pipeline = [
  ['AUTHORIZED TARGET', Fingerprint], ['ASSET VALIDATION', ShieldCheck], ['SECURITY SCAN', ScanLine],
  ['SECRET DETECTION', KeyRound], ['DEPENDENCY ANALYSIS', PackageCheck], ['RISK ENGINE', Radar],
  ['FINDINGS', FileSearch], ['REPORT', FileSearch],
] as const;
const findings = [
  ['CRITICAL', 'Hardcoded API Credential', 'Secrets', '98%'], ['HIGH', 'Vulnerable Flask Dependency', 'Dependency', '96%'],
  ['HIGH', 'Insecure Configuration', 'Configuration', '91%'], ['MEDIUM', 'Weak Security Header', 'Web Security', '87%'],
];

function Brand() {
  return <Link href="/" className="flex items-center gap-3" aria-label="CyberShield AI home"><span className="landing-brand-mark"><Shield className="h-4 w-4" /></span><span><span className="block text-sm font-semibold tracking-tight text-white">CyberShield AI</span><span className="block text-[10px] uppercase tracking-[0.18em] text-slate-500">AI-Powered Security Platform</span></span></Link>;
}

export default function RootPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  const anchor = (label: string) => `#${label.toLowerCase().replaceAll(' ', '-')}`;
  return <main className="landing-page overflow-hidden">
    <nav className="landing-nav"><div className="landing-container flex h-20 items-center justify-between"><Brand /><div className="hidden items-center gap-8 md:flex">{['Features', 'How It Works', 'Security', 'About'].map((item) => <a key={item} href={anchor(item)} className="landing-nav-link">{item}</a>)}</div><div className="hidden items-center gap-3 md:flex"><Link href="/login" className="landing-text-button">Sign In</Link><Link href="/register" className="landing-button landing-button-small">Get Started <ArrowRight className="h-4 w-4" /></Link></div><button type="button" className="landing-icon-button md:hidden" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="landing-mobile-menu md:hidden"><div className="landing-container flex flex-col gap-5 py-6">{['Features', 'How It Works', 'Security', 'About'].map((item) => <a key={item} href={anchor(item)} onClick={closeMenu} className="landing-nav-link">{item}</a>)}<div className="flex gap-3 border-t border-white/10 pt-5"><Link href="/login" onClick={closeMenu} className="landing-text-button">Sign In</Link><Link href="/register" onClick={closeMenu} className="landing-button landing-button-small">Get Started <ArrowRight className="h-4 w-4" /></Link></div></div></div>}</nav>

    <section className="landing-hero landing-grid-bg"><div className="landing-container relative grid items-center gap-14 py-20 lg:grid-cols-[1fr_0.88fr] lg:gap-20 lg:py-28"><div className="landing-reveal"><div className="landing-eyebrow"><span className="landing-status-dot" /> SECURITY INTELLIGENCE FOR MODERN TEAMS</div><h1 className="landing-display mt-7">Find vulnerabilities <span>before attackers do.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">AI-powered security testing for source code, websites, secrets, and dependencies, built to help teams identify, prioritize, and remediate security risks faster.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/register" className="landing-button">Start Scanning <ArrowRight className="h-4 w-4" /></Link><a href="#platform-preview" className="landing-outline-button">Explore Platform <ChevronDown className="h-4 w-4" /></a></div><div className="mt-12 flex items-center gap-3 text-xs text-slate-500"><LockKeyhole className="h-4 w-4 text-cyan-400" /> Built for authorized security testing <span className="h-1 w-1 rounded-full bg-slate-600" /> No credentials exposed</div></div>
      <div id="platform-preview" className="landing-dashboard landing-reveal-delay"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-cyan-400" /><span className="text-xs font-medium text-slate-300">SECURITY OVERVIEW</span></div><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-emerald-300">Illustrative preview</span></div><div className="grid gap-5 p-5 sm:grid-cols-[1.1fr_0.9fr]"><div className="landing-score-panel"><div className="flex items-center justify-between"><span className="text-xs text-slate-400">Security Score</span><span className="text-xs text-emerald-300">+8.4%</span></div><div className="mt-5 flex items-end gap-2"><strong className="text-6xl font-semibold tracking-[-0.08em] text-white">85</strong><span className="mb-2 text-sm text-slate-500">/100</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-[85%] rounded-full bg-gradient-to-r from-cyan-400 to-emerald-400" /></div><p className="mt-3 text-xs text-slate-500">Good posture · improvements recommended</p></div><div className="grid grid-cols-2 gap-2">{[['Critical', '2', 'text-red-300'], ['High', '7', 'text-orange-300'], ['Medium', '14', 'text-amber-300'], ['Low', '23', 'text-cyan-300']].map(([label, value, color]) => <div key={label} className="landing-mini-stat"><span className={`text-xl font-semibold ${color}`}>{value}</span><span className="mt-1 text-[10px] uppercase tracking-wider text-slate-500">{label}</span></div>)}</div></div><div className="border-t border-white/10 px-5 py-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs text-slate-400">Active analysis</span><span className="text-[10px] uppercase tracking-widest text-slate-600">Demo data</span></div><div className="space-y-3">{['Production API', 'Source Code', 'Dependencies'].map((name) => <div key={name} className="flex items-center justify-between text-xs"><span className="text-slate-300">{name}</span><span className="flex items-center gap-2 text-emerald-300"><CircleCheck className="h-3.5 w-3.5" /> COMPLETED</span></div>)}</div></div><div className="landing-scan-line" /></div></div></section>

    <section className="border-y border-white/10 bg-slate-950/60"><div className="landing-container flex flex-col gap-5 py-7 lg:flex-row lg:items-center lg:justify-between"><p className="text-sm font-medium text-slate-300">One platform. Multiple layers of security.</p><div className="flex flex-wrap gap-2">{capabilities.map((item) => <span key={item} className="landing-capability"><Check className="h-3 w-3 text-cyan-400" />{item}</span>)}</div></div></section>

    <section id="features" className="landing-section"><div className="landing-container"><div className="landing-section-heading"><div><div className="landing-kicker">COVERAGE THAT CONNECTS</div><h2 className="landing-heading mt-3">Security testing from<br /><span>code to production.</span></h2></div><p>See the full picture across the attack surface you own, with context your team can act on.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, number, title, description }) => <article key={title} className="landing-feature-card"><div className="flex items-start justify-between"><span className="landing-feature-icon"><Icon className="h-5 w-5" /></span><span className="text-xs text-slate-600">{number}</span></div><h3 className="mt-9 text-lg font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p><ArrowRight className="mt-7 h-4 w-4 text-slate-600" /></article>)}</div></div></section>

    <section id="how-it-works" className="landing-section border-y border-white/10 bg-slate-950/45"><div className="landing-container"><div className="landing-kicker">A CLEARER SECURITY LOOP</div><h2 className="landing-heading mt-3">From target to <span>actionable security.</span></h2><div className="mt-14 grid gap-4 md:grid-cols-4">{steps.map(({ icon: Icon, title, description }, index) => <div key={title} className="relative"><div className="landing-step-number">0{index + 1}</div><Icon className="h-5 w-5 text-cyan-300" /><h3 className="mt-6 font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p>{index < steps.length - 1 && <ArrowRight className="absolute right-3 top-1 hidden h-4 w-4 text-slate-700 md:block" />}</div>)}</div></div></section>

    <section id="security" className="landing-section"><div className="landing-container"><div className="landing-section-heading"><div><div className="landing-kicker">PIPELINE VISIBILITY</div><h2 className="landing-heading mt-3">Every check,<br /><span>one connected flow.</span></h2></div><p>Each authorized asset moves through the same visible security workflow, from validation to report.</p></div><div className="landing-pipeline mt-14">{pipeline.map(([label, Icon], index) => <div key={label} className="landing-pipeline-item"><div className="landing-pipeline-node"><Icon className="h-4 w-4" /></div><span>{label}</span>{index < pipeline.length - 1 && <div className="landing-pipeline-line" />}</div>)}</div></div></section>

    <section id="about" className="landing-section border-y border-white/10 bg-slate-950/45"><div className="landing-container grid gap-12 lg:grid-cols-[0.72fr_1.28fr] lg:items-start"><div><div className="landing-kicker">FINDINGS, WITHOUT THE NOISE</div><h2 className="landing-heading mt-3">Know what needs<br /><span>attention first.</span></h2><p className="mt-6 max-w-sm text-sm leading-7 text-slate-400">Illustrative findings show how CyberShield AI organizes severity, confidence, and status into a focused workflow.</p><Link href="/findings" className="landing-link-button mt-8">View Security Findings <ArrowRight className="h-4 w-4" /></Link></div><div className="landing-table-wrap"><div className="hidden grid-cols-[0.7fr_1.5fr_1fr_0.7fr_0.6fr] gap-3 border-b border-white/10 px-5 py-4 text-[10px] uppercase tracking-widest text-slate-600 sm:grid"><span>Severity</span><span>Finding</span><span>Category</span><span>Confidence</span><span>Status</span></div>{findings.map(([severity, finding, category, confidence]) => <div key={finding} className="grid gap-2 border-b border-white/5 px-5 py-4 last:border-0 sm:grid-cols-[0.7fr_1.5fr_1fr_0.7fr_0.6fr] sm:items-center sm:gap-3"><span className={`w-fit text-[10px] font-semibold uppercase tracking-wider ${severity === 'CRITICAL' ? 'text-red-300' : severity === 'HIGH' ? 'text-orange-300' : 'text-amber-300'}`}>{severity}</span><span className="text-sm font-medium text-slate-200">{finding}</span><span className="text-xs text-slate-500">{category}</span><span className="text-xs text-slate-400">{confidence}</span><span className="flex items-center gap-1.5 text-xs text-slate-400"><span className="h-1.5 w-1.5 rounded-full bg-orange-300" /> Open</span></div>)}</div></div></section>

    <section className="landing-section"><div className="landing-container grid gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><div className="landing-kicker">POSTURE AT A GLANCE</div><h2 className="landing-heading mt-3">Measure the work<br /><span>that matters.</span></h2><p className="mt-6 max-w-sm text-sm leading-7 text-slate-400">Static preview values illustrate how teams can track security posture across each layer.</p></div><div className="landing-posture"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-center"><div><span className="text-xs uppercase tracking-widest text-slate-500">Security Posture</span><div className="mt-3 flex items-baseline gap-2"><strong className="text-7xl font-semibold tracking-[-0.09em] text-white">85</strong><span className="text-sm text-slate-500">/100</span></div><span className="mt-2 block text-sm text-emerald-300">Good · Improvements Recommended</span></div><div className="landing-ring"><span>85</span></div></div><div className="mt-8 grid gap-5 sm:grid-cols-4">{[['Code Security', '91%', 'w-[91%]'], ['Dependency Security', '78%', 'w-[78%]'], ['Secret Security', '94%', 'w-[94%]'], ['Web Security', '82%', 'w-[82%]']].map(([label, value, width]) => <div key={label}><div className="flex justify-between text-xs"><span className="text-slate-400">{label}</span><span className="text-slate-300">{value}</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-800"><div className={`h-full rounded-full bg-cyan-400 ${width}`} /></div></div>)}</div></div></div></section>

    <section className="landing-section border-y border-white/10 bg-slate-950/45"><div className="landing-container grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><div className="landing-kicker">CONTEXT FOR EVERY FINDING</div><h2 className="landing-heading mt-3">Turn security findings<br /><span>into clear actions.</span></h2><p className="mt-6 max-w-lg text-sm leading-7 text-slate-400">Security findings are easier to understand when they come with context. Use AI-assisted analysis to understand impact and identify practical remediation steps.</p></div><div className="landing-ai-panel"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-3"><span className="landing-feature-icon"><Sparkles className="h-4 w-4" /></span><div><p className="text-sm font-medium text-white">AI Security Analysis</p><p className="text-xs text-slate-500">Illustrative preview</p></div></div><span className="rounded-full bg-cyan-400/10 px-2 py-1 text-[10px] font-medium text-cyan-300">READY</span></div><div className="mt-6 grid gap-5 sm:grid-cols-[0.7fr_1.3fr]"><div><span className="text-[10px] uppercase tracking-widest text-slate-600">Finding</span><p className="mt-2 text-sm font-medium text-slate-200">Vulnerable Dependency</p></div><div><span className="text-[10px] uppercase tracking-widest text-slate-600">AI Analysis</span><p className="mt-2 text-sm leading-6 text-slate-400">This dependency version contains a known security vulnerability. Upgrade to a patched version and verify that dependent packages remain compatible.</p></div></div><div className="mt-6 flex flex-col gap-3 border-t border-white/10 pt-5 sm:flex-row sm:items-center sm:justify-between"><span className="text-xs text-slate-500">Recommended action: <strong className="font-medium text-slate-300">Upgrade dependency</strong></span><button type="button" className="landing-outline-button">Analyze Finding <ArrowRight className="h-4 w-4" /></button></div></div></div></section>

    <section className="landing-section"><div className="landing-container"><div className="landing-responsible"><div><div className="landing-kicker">RESPONSIBLE BY DESIGN</div><h2 className="landing-heading mt-3">Built for authorized<br /><span>security testing.</span></h2><p className="mt-5 max-w-xl text-sm leading-7 text-slate-400">CyberShield AI is designed for security testing of systems, applications, source code, and assets that you own or are explicitly authorized to assess.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['AUTHORIZED ASSETS', 'SECURE ANALYSIS', 'ACTIONABLE FINDINGS', 'RESPONSIBLE SECURITY'].map((label) => <div key={label} className="landing-responsible-item"><Check className="h-4 w-4 text-emerald-300" /><span>{label}</span></div>)}</div></div></div></section>

    <section className="landing-cta"><div className="landing-container relative py-24 text-center"><div className="landing-kicker justify-center">READY WHEN YOU ARE</div><h2 className="landing-display mx-auto mt-5 max-w-3xl">Ready to strengthen your <span>security posture?</span></h2><p className="mx-auto mt-6 max-w-xl text-base leading-7 text-slate-400">Scan your authorized assets, discover security risks, and turn findings into actionable remediation.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/register" className="landing-button">Get Started <ArrowRight className="h-4 w-4" /></Link><a href="http://localhost:8000/docs" className="landing-outline-button">View Documentation <ArrowRight className="h-4 w-4" /></a></div></div></section>

    <footer className="border-t border-white/10"><div className="landing-container flex flex-col gap-10 py-12 md:flex-row md:items-end md:justify-between"><div><Brand /><p className="mt-5 max-w-xs text-sm leading-6 text-slate-500">AI-powered cybersecurity assessment and risk analysis.</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-500"><a href="#features" className="hover:text-white">Features</a><a href="#how-it-works" className="hover:text-white">How It Works</a><a href="#security" className="hover:text-white">Security</a><a href="http://localhost:8000/docs" className="hover:text-white">Documentation</a><Link href="/login" className="hover:text-white">Sign In</Link></div></div><div className="landing-container border-t border-white/5 py-5 text-xs text-slate-600">© 2026 CyberShield AI. Built for authorized security testing.</div></footer>
  </main>;
}